version: "3"
services:
  nginx:
    container_name: project_6
    build:
      context: .
      dockerfile: deploy/nginx/Dockerfile
    volumes:
      - ./deploy/nginx/templates:/etc/nginx/templates
      - ./project_6:/data/project_6
    ports:
      - "8081:80"
  php:
    container_name: project-php
    build:
      context: .
      dockerfile: deploy/php-fpm/Dockerfile
    volumes:
      - ./project_6:/data/project_6