security:
    encoders:
        # this internal class is used by Symfony to represent in-memory users
        Symfony\Component\Security\Core\User\User: 'auto'

    providers:
        backend_users:
            memory:
                users:
                    admin: { password: '$argon2id$v=19$m=65536,t=4,p=1$XlmfwpisnnqRmD7rzGqLNQ$k7YygV2V+ch8NB+9tLD4W336YunOz/ijNzNO/KLX42Q', roles: ['ROLE_ADMIN'] } #qwerty1
                    user: { password: '$argon2id$v=19$m=65536,t=4,p=1$XlmfwpisnnqRmD7rzGqLNQ$k7YygV2V+ch8NB+9tLD4W336YunOz/ijNzNO/KLX42Q', roles: ['ROLE_USER'] } #qwerty1
                    #  admin: { password: '$argon2id$v=19$m=65536,t=4,p=1$H2fK4V4oi7Lz16fg4pxRCg$eOymiNtdBKvstPmfrkdkXNfLFeosV5Q6PA3mWLiFXsE', roles: ['ROLE_ADMIN'] } #qwerty

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/api/
            anonymous: false
            provider: backend_users
            http_basic:
                realm: Secured Area

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true



    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/api, roles: ROLE_ADMIN }
